# Generated by Django 2.2.1 on 2019-06-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='desc',
        ),
    ]
